"""empty message

Revision ID: 19546c41a5f5
Revises: 47e2b0c855c5
Create Date: 2015-12-30 23:40:33.267271

"""

# revision identifiers, used by Alembic.
revision = '19546c41a5f5'
down_revision = '47e2b0c855c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
