"""empty message

Revision ID: 19af3f0db7a9
Revises: 38bfdbdca2da
Create Date: 2015-12-30 15:09:41.442821

"""

# revision identifiers, used by Alembic.
revision = '19af3f0db7a9'
down_revision = '38bfdbdca2da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.UnicodeText(), nullable=True),
    sa.Column('longitude', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map')
    ### end Alembic commands ###
