"""empty message

Revision ID: 38bfdbdca2da
Revises: 35e1fbc289fc
Create Date: 2015-12-29 18:48:26.315104

"""

# revision identifiers, used by Alembic.
revision = '38bfdbdca2da'
down_revision = '35e1fbc289fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('split_panels', sa.Column('content', sa.String(length=1024), nullable=True))
    op.add_column('split_panels', sa.Column('title', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('split_panels', 'title')
    op.drop_column('split_panels', 'content')
    ### end Alembic commands ###
