"""empty message

Revision ID: 3e3cbdea05f1
Revises: 413febbf920b
Create Date: 2015-12-29 15:15:02.899113

"""

# revision identifiers, used by Alembic.
revision = '3e3cbdea05f1'
down_revision = '413febbf920b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carousel_images', sa.Column('carousel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carousel_images', 'carousels', ['carousel_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carousel_images', type_='foreignkey')
    op.drop_column('carousel_images', 'carousel_id')
    ### end Alembic commands ###
