"""empty message

Revision ID: 413febbf920b
Revises: 2a77902502cf
Create Date: 2015-12-29 15:14:03.331348

"""

# revision identifiers, used by Alembic.
revision = '413febbf920b'
down_revision = '2a77902502cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousel_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_link', sa.String(length=255), nullable=True),
    sa.Column('image_caption', sa.String(length=255), nullable=True),
    sa.Column('image_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carousels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carousels')
    op.drop_table('carousel_images')
    ### end Alembic commands ###
