"""empty message

Revision ID: 47e2b0c855c5
Revises: 19af3f0db7a9
Create Date: 2015-12-30 23:38:46.273331

"""

# revision identifiers, used by Alembic.
revision = '47e2b0c855c5'
down_revision = '19af3f0db7a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=True),
    sa.Column('grid_type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grid_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['grids.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grid_pages')
    op.drop_table('grids')
    ### end Alembic commands ###
