"""empty message

Revision ID: 51a4d584cc20
Revises: 19546c41a5f5
Create Date: 2015-12-31 00:09:05.121119

"""

# revision identifiers, used by Alembic.
revision = '51a4d584cc20'
down_revision = '19546c41a5f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('header_image', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'header_image')
    ### end Alembic commands ###
