"""empty message

Revision ID: 585003100816
Revises: 8a1bcdfcbf2
Create Date: 2015-12-31 00:53:33.186447

"""

# revision identifiers, used by Alembic.
revision = '585003100816'
down_revision = '8a1bcdfcbf2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
