"""empty message

Revision ID: 8a1bcdfcbf2
Revises: 51a4d584cc20
Create Date: 2015-12-31 00:43:51.995916

"""

# revision identifiers, used by Alembic.
revision = '8a1bcdfcbf2'
down_revision = '51a4d584cc20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
